### ISSUE TITLE
Feedback! Shift+F9 should be F2

### ISSUE THREAD

**Issue by standoski** [Woundorf/foxreplace#190]
Hello!

As I see in FF 49 the F2 isn't used for any shortcut. In the old good days the F2 was the default key for Foxreplace.

Honestly, I use F2 for 'Replace with substitution list' not the Shift-F9 until FF start to apply the signed version for addons. (i modified at every update de xul file to use F2, butt with the signed addon can't be modified and work in FF and I don't want to use the Nightly or Developer version of FF)

Can you make the old behavior for 'Replace with substitution list' to be the F2?

Thanks!

PS: Or PLEASE make an option to LET THE USERS to chose the keys combination that want to use, what do you think?
PS2: In FF49.0.1 the Foxreplace 0.17.2 don't work and the 0.17.3 is not approved by days :(

**Comment by Woundorf** [comment]
F2 is not used but Shift+F2 is used to show the developer toolbar. I prefer that both shortcuts in FoxReplace (show the replace bar and apply the substitution list) are mapped to the same F key, that's why I use F9, although it's a little antiergonomic.

I will consider a shortcut customization option when I port to WebExtensions, but you can already change any shortcut with this other addon: https://addons.mozilla.org/firefox/addon/keybinder/

> PS2: In FF49.0.1 the Foxreplace 0.17.2 don't work and the 0.17.3 is not approved by days :(

I don't know why it's taking so long. The previous version was approved in 1 day.

**Comment by standoski** [comment]
Marc you're the man of the day :P and Keybinder is the God :))
Thank you for this and I don't care about the implementation of that option, but yes it will be nice to have it for Chrome too this addon.
Cheers!
