### ISSUE TITLE
some characters disable rules

### ISSUE THREAD

**Issue by lvmm** [Woundorf/foxreplace#194]
Consider a rule with HTML conversion set for Input&Output and a plain text replacement being applied to a web page with the usual '<meta http-equiv="Content-Type"' header in it. Replacing 'meta' with 'proto' works producing '<proto http-equiv="Content-Type"' but replacing '<meta' with '<proto' doesn't work, also replacing 'http-equiv' works but 'http-equiv=' doesn't. Tried escaping < and = with a backslash but it didn't help. How can I specify search targets with these characters?

**Comment by Woundorf** [comment]
I have tried and it works in boths cases. What FoxReplace and Firefox versions are you using?

**Comment by lvmm** [comment]
Firefox 49.0.2 win-32, foxreplace 0.17.3

**Comment by Woundorf** [comment]
Strange then, I have the same versions but it works for me.

**Comment by lvmm** [comment]
Well, not for me. The configuration is as simple as it gets - just one rule, and it doesn't work, but if you remove the < it works like a charm. I am checking by viewing the page source (^u). Tried disabling other addons - didn't help.

{
  "version": "0.15",
  "groups": [
    {
      "name": "test",
      "urls": [
        "mozilla.org"
      ],
      "substitutions": [
        {
          "input": "<meta",
          "inputType": "text",
          "output": "<proto",
          "caseSensitive": false
        }
      ],
      "html": "inputoutput",
      "enabled": true
    }
  ]
}

BTW while it says version 0.15 in the export file but  0.17.3 in about:addons.

**Comment by Woundorf** [comment]
Now that I have thought of it, I think that you are misunderstanding what happens.

If you apply the substitutions on the page with your example, it works. You can check it with the inspector (shift+ctrl+c), but not with your specific example because ```<proto>``` is not a valid HTML element and thus is ignored, but if you replace for example ```<meta``` with ```<link``` you will see the change in the inspector.

What you are doing instead, as I understand it now, is applying the substitutions in the "View source" page, but that is an entirely different thing, it's an HTML document that shows the source of the other HTML document. If you open the inspector here you will see that the colored ```<meta``` is in reality ```&lt;<span class="start-tag">meta</span>```. That's why it's not changed when trying to replace ```<meta```.

**Comment by Woundorf** [comment]
> BTW it says version 0.15 in the export file but 0.17.3 in about:addons.

The 0.15 refers to the version of the save format, which in this case was last changed in version 0.15.0.

**Comment by lvmm** [comment]
Replacing <meta with <link doesn't work for me either but replacing meta with link still does. I've ran into this problem - rules with '<' in search strings not working, when trying to remove xml ads embedded into the page, this <meta stuff is the result of trying to reduce this problem to the most basic form.

And I am not sure about bringing in the inspector into this discussion - it is some heavily formatted and modified document which has little relation to the raw html received from the server and visible in the source window. If you download the document without involving firefox at all - say, with wget or curl, and compare it to the source you'll find that they match and that what's visible in the inspector window is wildly different. I hope foxreplace does process the raw html before firefox messes with it?

**Comment by Woundorf** [comment]
Maybe I didn't express it well. What I mean is that the changes you do to the "View source" page are unrelated to the original page. The document in the "View source" page is an HTML document that displays the source of the original page with syntax highlighting, but it's not the source itself. If you change anything in the "View source" tab it won't affect the original page in the other tab. And substitutions that work in one place don't work (in general) in the other. You can't change ```<meta``` in the "View source" tab because there isn't any ```<meta>``` element in its source, and I mean its own source, not the source that it's displaying (it's a bit confusing, I know).

With the inspector you can see the real DOM structure after parsing, and you can open it in the original page and also in the "View source" page (and with the Developer Edition you can also inspect the inspector from another window). The only way to check if a substitution works or not in the real page is with the inspector, because if you hit ctrl+u to view the source after modifying it you will see the unmodified source, always.

BTW, I was wrong in saying that ```<proto>``` is ignored, it is instead moved to inside the ```<body>``` when parsed by Firefox.

> I hope foxreplace does process the raw html before firefox messes with it?

It doesn't process the raw HTML, it only works at the DOM level, i.e. after Firefox has parsed the HTML.

**Comment by lvmm** [comment]
Of course I was not trying to change anything in the source window myself, I was using it to check the results of foxreplace's work and when I say that the rule works I mean that when I open the page source I can see that all metas have been replaced by proto. But if you say that foxreplace works on the DOM level... bummer. At least in my case it turns a simple task of altering a few tags into an absolute horror of modifying a forest of featureless multilevel nested divs.

Ok, feature request: make it work on the HTML level. PLEASE.

**Comment by Woundorf** [comment]
> Ok, feature request: make it work on the HTML level. PLEASE.

I don't know if it's even possible, but I will investigate it in the future. First I have to port to WebExtensions.
