### ISSUE TITLE
Doesn't affect certain fields

### ISSUE THREAD

**Issue by Morokei2** [Woundorf/foxreplace#202]
First, thank you for the great add-on. Unfortunately, I noticed that it doesn't work with certain types of fields. For example, it won't replace text in the "title" field on the Youtube upload page:

![test](https://cloud.githubusercontent.com/assets/25304941/22219052/5351333a-e1ba-11e6-83ae-07f5227f5b9a.jpg)

I tried html and plain text methods, but none of them work. Is there any way to make it to work with this particular field?

**Comment by Woundorf** [comment]
I don't know exactly why it isn't replaced, but it looks like it uses some weird HTML. I'll investigate it in more detail when I can.

**Comment by sqgl2** [comment]
I found the same but when I tried CTRL-U Firefox *does* show the FoxReplaced changes (they just were ignored when FireFox displayed the html). 

Have attached an html file which is my admin page for an internet radio station. The problem happens when I try to change the IP address displayed for a listener so to test it you would need my admin rights - therefore you cannot test it.

Perhaps by simply looking at the html I have attached you can see what the problem is. Note that every time I force a FoxReplace substitution it _is_ applied for about half a second then the FoxReplace substitution is undone (probably due to the way the html is auto refreshed in the javascript). I even tried replacing the word "script" with "XXX" which should have made the html error riddled but it did nothing.

[foxreplace_bug.htm.txt](https://github.com/Woundorf/foxreplace/files/869771/foxreplace_bug.htm.txt)

**Comment by Woundorf** [comment]
Ok, I'll take a look to it in the future. Currently my top priority is porting FoxReplace to WebExtensions since it will be the only model supported by Firefox in November.
