### ISSUE TITLE
Newest update broke previously working website + Statusbar icon

### ISSUE THREAD

**Issue by kazerniel** [Woundorf/foxreplace#213]
Hi, my replacements on SteamGifts.com were working perfectly before, but this newest update completely broke the site's navigation and popups.

Also, I regularly used the little icon on the statusbar to toggle FoxReplace on and off, but now the icon has disappeared, and I can't find an option to put it back (including FF's Customize menu).

Could you help? (I'm using Firefox 54.0 btw.)

**Comment by Woundorf** [comment]
Hi, sorry for the inconvenience.

The first problem is strange because the replacement logic has not changed, it's just the same code moved to another place. Could it be a coincidental change in that website? If you could try again with the previous version to verify that the problem does not happen I would be grateful. (To do this you should uninstall FoxReplace and then install the previous version from [here](https://addons.mozilla.org/firefox/addon/foxreplace/versions/).) If you can't try this or you can confirm that is a problem with the new version, then I would need an example substitution list and what settings are you using, and a specific page where something is broken (and tell me what happens and what should happen if it isn't evident at first glance).

And the problem with the icon, you are the second user to report it, so I suppose it affects few users. I haven't had this problem myself, so I don't know what is happening. I have a few ideas to try to see if it reappears in its place or in the Customize menu:

1. Restart Firefox
2. Uninstall and then install again FoxReplace (maybe with a Firefox restart in between to be sure)
3. As a last resort, use the "Restore defaults" button in the Customize menu

I hope this can help.

**Comment by SaltatorMortis** [comment]
same here
but asimple re-install + Restore defaults had fixed this problem for me...

**Comment by Merseybuoy** [comment]
Hi, I'm also missing the icon with version 1.0. Tried reinstalling without success. Restore Defaults is too severe for me, so reverted to 0.17.3. Using Firefox 55 b3 64bit.

**Comment by kazerniel** [comment]
Sorry for the late reply. I uninstalled the new version, restarted FF, then reinstalled the 0.17 version, and now it's back to working well, and the icon is back on the statusbar again :) So I guess I'll stick with this version for now.

**Comment by Woundorf** [comment]
Great news then :)

**Comment by Woundorf** [comment]
Sorry, I misunderstood the answer and thought it worked with 1.0 after reinstall. I will release a new version soon that should fix the toolbar button problem.

**Comment by Merseybuoy** [comment]
Version 1.1.3 fixes the toolbar button for me.  Thank you.

**Comment by taxen** [comment]
Version 1.1.3 + FF 55.0.3 erases all the previous data, but restores toolbar button for me. Totally at loss.

**Comment by Woundorf** [comment]
It should not erase data. The whole point of this release is to import the data from the old extensions API to the new one.

Have you seen any message in the error console (Ctrl+Shift+J) just after the update?

In any case, the old settings must still be saved (1.1.3 copies the settings and saves them in the new format, but the old ones are still kept), so if you install the old version, everything should be fine again.

Alternatively, you can import the old substitution list from the file where it was saved in the previous versions. Go to about:profiles and open your profile directory from there. There you will find a foxreplace directory and inside it a file named list.json (there must also be a list-backup.json that should have been created while migrating data). Import it and you will recover your substitution list. The other settings are mostly checkboxes, and some numbers, so I suppose you can remember their states (otherwise you can go to about:config and type foxreplace in the filter box to see all previous settings).

**Comment by Merseybuoy** [comment]
Taxen, Your data may seem to have disappeared until you restart Firefox.  That was my case.  Otherwise, as Woundorf says, installing your previous version will bring it back.

**Comment by taxen** [comment]
Woundorf, as Merseybuoy told me, restart just fixed my problem! Thank you all!
