### ISSUE TITLE
Unable to enable/disable lists in FoxReplace

### ISSUE THREAD

**Issue by sdoeden** [Woundorf/foxreplace#217]
Longtime user, big fan! I have recently become unable to enable/disable lists in FoxReplace. I've tried restarting the browser, updating browser, updating FoxReplace, disabling/enabling FoxReplace, and cursing the heavens. Any quick fix for this?

**Comment by Woundorf** [comment]
I now see that it also happens to me. But, to be precise, it's only the checkmarks that are not visible, but you can still enable and disable each group by clicking in the main view or by opening it and using the checkbox in the top right. There you can see if it's enabled or not.

I don't know the cause, but I must be some change in Firefox because I haven't touched anything in that part in a long time.

Anyway, in few days a new version of FoxReplace will be approved and will come with a completely new options page that won't have this problem (it will probably have some other problems, but I hope there's nothing major).
