### ISSUE TITLE
How to put "comments" in .json file

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#228]
Is there any method that we can put our "comments" in the .json file, that fr can ignore.

I mean, I need to put "Date", "Folder/ File name where I am having master xlsx file of this .json file" so on.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
There is no support for comments in JSON.

But you can add any field you want that is not supported by FoxReplace and it will be ignored. This also means that if then you export this list from FoxReplace the information will be lost, as it is simply not read.

Otherwise you could add it in a group name/description.
