### ISSUE TITLE
No multiline modifier for dot

### ISSUE THREAD

**Issue by tedych** [Woundorf/foxreplace#246]
Tried many ways but couldn't make this extension catch multilines with the dot character. No documentation.
How do I make dot work on multiline strings? HTML is "very" multiline by default.
Tried (?s), (?s:.+?) to no avail. Please advise.

**Comment by Woundorf** [comment]
Hi, if I understand your request, you want the dot character to match the newline character, right? This is not possible in JavaScript (see documentation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes)), but you can use [^] instead of the dot character to match any character.

There's another possible interpretation, that you want something like the [multiline flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters) of JavaScript RegExp:

> multiline; treat beginning and end characters (^ and $) as working over multiple lines (i.e., match the beginning or end of _each_ line (delimited by \n or \r), not only the very beginning or end of the whole input string)

If this is the case, then it's currently not implemented, but there's already a request for it in #95.

**Comment by tedych** [comment]
Thanks, Woundorf. The [^} seems to have done the job.
Yes, I mean the DOTALL flag, and not the "m" flag which affects ^ and $ line boundaries in a larger string. I appologize if my explanation wasn't correct.
While maybe not strictly a bug, still an issue for me. If I try to use (?s) or (?s:.....), it throws error in red.
My use case was to hide some large div with complex internal structures. E.g. replace it with empty string.
Something like this
<div class="abc\s.+?">.+?<a class="def".+?> (just quick example)
where .+? between tags should match many newlines.
After some new features added to adblock and ublock origin (-abp-has()) I just realised they are better suited for my use case.

**Comment by SaltatorMortis** [comment]
the reason why it throws error is because this "inline flag" Feature is not a native in JS RegExp
it only gets added if you use XregExp (and then it is only translated into [\s\S] )

**Comment by tedych** [comment]
I see, thanks. I was a bit upset after trying to set thing up by myself only, but now I know JS does not support normal regex, although I use JS but never happened to need it to support these flags to date, so...
