### ISSUE TITLE
What is meant by "Enabled translation" in v2.0.0 change notes?

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#299]
I read in change notes - 

```
v2.0.0 (2017-10-13)
    Enabled translation.
```

What is meant by that? 
I don't see any translation-related option in entire UI.

I am asking whether it means translation of foxreplace UI are available?
If so, where are they stored and how can I check whether one is available in my mothertongue (Hindi) and how to select that, or if not available, which file to localize to my language and send to you?

Thanks.

**Comment by Woundorf** [comment]
It means that it is translatable. Pre-WebExtensions versions were localized in several languages thanks to Babelzilla. With WebExtensions they had to be dropped because they are structurally very different.

Currently FoxReplace is available in Catalan and English. I want to set up an online translation tool (probably with Weblate), but I haven't done it yet.

If you want to translate it to Hindi now you can translate it on your computer and then create a pull request or send me the file. Translations are stored into the _locales folder, with a subfolder for each locale and a messages.json file inside it. For Hindi you should create a subfolder called hi or hi-IN and a translated version of messages.json inside it.
