### ISSUE TITLE
[query] how to make fr skip something (not convert it as per tables)

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#313]
This is not a issue or bug or anything, just a help request to know whether any method exists in fr or in regular expressions to acomplish this.

I am doing English Hindi translation. After my tables convert everything known so far to me, I have put fr table entries to convert all individual English alphabets (abcd...xyz) to my Hindi devanagari script.

a ए
b बी
c सी

But that will also convert http, www, emailaddresses, websites etc also that I want to retain as such in English.

Is there method in fr or in re or trick that can force fr to skip conversion of something even if it is matching some valid entry in tables.

then I can add thus tagged entries for www, http, known websites and emails in my tables, before individual alphabet conversion and it will not be converted to corresponding Hindi Hindi script.

say can "http" be taggest in someway in fr table entries so that if "h" "t" or "p" conversion command appears later on, http is not converted due to effect of such a tag.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment]
In regular expressions there is the concept of lookahead and lookbehind. You can take a look here for example: https://www.regextutorial.org/positive-and-negative-lookahead-assertions.php. Maybe you can achieve something with this like in this question in Stack Overflow: https://stackoverflow.com/questions/8408152/regular-expression-negative-match. Hope this helps.

Note that lookahead is supported in Firefox since always but lookbehind in Javascript is a recent specification and I don't know if it's already supported in Firefox or not, you'll have to research or try it.
